#ifndef DOS9_MODULES_H
#define DOS9_MODULES_H

#include <libDos9.h>

extern void*(*Dos9_GetSymbol)(int);
extern void(*Dos9_SetEnv)(const char*, const char*);
extern char*(*Dos9_GetEnv)(const char*);
extern const char*(*Dos9_GetCurrentDir)(void);
extern int(*Dos9_SetCurrentDir)(const char*);
extern FILE*(*Dos9_GetfInput)(void);
extern FILE*(*Dos9_GetfOutput)(void);
extern FILE*(*Dos9_GetfError)(void);
extern int(*Dos9_GetbIsScript)(void);

extern char*(*Dos9_GetNextParameterEs)(const char*, ESTR*);
extern char*(*Dos9_EsToFullPath)(ESTR*);
extern int(*Dos9_RegisterCommand)(const char*, int(*handler)(char*));
extern void(*Dos9_ShowErrorMessage)(int,const char*,int);

#define fError Dos9_GetfError()
#define fOutput Dos9_GetfOutput()
#define fInput Dos9_GetfInput()

#define DOS9_MOD_API_VERSION 0

enum {
  DOS9_NO_ERROR = 0,
  DOS9_FILE_ERROR,
  DOS9_DIRECTORY_ERROR,
  DOS9_COMMAND_ERROR,
  DOS9_UNEXPECTED_ELEMENT,
  DOS9_BAD_COMMAND_LINE,
  DOS9_LABEL_ERROR,
  DOS9_EXTENSION_DISABLED_ERROR,
  DOS9_EXPECTED_MORE,
  DOS9_INCOMPATIBLE_ARGS,
  DOS9_UNABLE_RENAME,
  DOS9_MATH_OUT_OF_RANGE,
  DOS9_MATH_DIVIDE_BY_0,
  DOS9_MKDIR_ERROR,
  DOS9_RMDIR_ERROR,
  DOS9_STREAM_MODULE_ERROR,
  DOS9_SPECIAL_VAR_NON_ASCII,
  DOS9_ARGUMENT_NOT_BLOCK,
  DOS9_FOR_BAD_TOKEN_SPECIFIER,
  DOS9_FOR_TOKEN_OVERFLOW,
  DOS9_FOR_USEBACKQ_VIOLATION,
  DOS9_FAILED_ALLOCATION,
  DOS9_CREATE_PIPE,
  DOS9_FOR_LAUNCH_ERROR,
  DOS9_FOR_BAD_INPUT_SPECIFIER,
  DOS9_FOR_TRY_REASSIGN_VAR,
  DOS9_INVALID_EXPRESSION,
  DOS9_INVALID_TOP_BLOCK,
  DOS9_UNABLE_DUPLICATE_FD,
  DOS9_UNABLE_CREATE_PIPE,
  DOS9_UNABLE_SET_ENVIRONMENT,
  DOS9_INVALID_REDIRECTION,
  DOS9_ALREADY_REDIRECTED,
  DOS9_MALFORMED_BLOCKS,
  DOS9_NONCLOSED_BLOCKS,
  DOS9_UNABLE_ADD_COMMAND,
  DOS9_UNABLE_REMAP_COMMANDS,
  DOS9_TRY_REDEFINE_COMMAND,
  DOS9_UNABLE_REPLACE_COMMAND,
  DOS9_UNABLE_SET_OPTION		,
  DOS9_COMPARISON_FORBIDS_STRING,
  DOS9_FAILED_FORK,
  DOS9_NO_MATCH,
  DOS9_NO_VALID_FILE,
  DOS9_INVALID_NUMBER,
  DOS9_TOO_MANY_ARGS,
  DOS9_INVALID_IF_EXPRESSION,
  DOS9_UNABLE_MOVE,
  DOS9_UNABLE_COPY,
  DOS9_UNABLE_DELETE,
  DOS9_UNABLE_MKDIR,
  DOS9_UNABLE_RMDIR,
  DOS9_MOVE_NOT_RENAME,
  DOS9_INVALID_CODEPAGE,
  DOS9_BREAK_ERROR,
  DOS9_INVALID_LABEL,
  DOS9_LOCK_MUTEX_ERROR,
  DOS9_RELEASE_MUTEX_ERROR,
  DOS9_UNABLE_CAT,
  DOS9_UNABLE_LOAD_MODULE,
  DOS9_INCOMPATIBLE_MODULE,
  DOS9_MODULE_LOADED,
  DOS9_ERROR_MESSAGE_NUMBER
};

#endif // DOS9_MODULES_H
